[package]
name = "rust-rt-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cpal = "0.16.0"
tracing = "0.1.41"
num-traits = "0.2.19"
clap = { version = "4.5.48", features = ["derive"] }
